<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DSK-4052" failures="1" tests="5" name="Default test" time="489.622" errors="0" timestamp="2025-08-12T11:13:09 IST">
  <testcase classname="newCar.FL.Acquisition_Quotes_FL_PCH_with_funder_quote_addition_without_maintenance_Test" name="aquisition_quotes_FL_PCH_OTR_calculation_without_maintenance_test" time="171.113"/>
  <testcase classname="newCar.FL.Acquisition_Quotes_FL_PCH_with_funder_quote_addition_without_maintenance_Test" name="aquisition_quotes_FL_PCH_after_discount_calculations_without_maintenance_test" time="4.342"/>
  <testcase classname="newCar.FL.Acquisition_Quotes_FL_PCH_with_funder_quote_addition_without_maintenance_Test" name="aquisition_quotes_FL_PCH_holding_cost_calculations_without_maintenance_test" time="30.379"/>
  <testcase classname="newCar.FL.Acquisition_Quotes_FL_PCH_with_funder_quote_addition_without_maintenance_Test" name="aquisition_quotes_FL_PCH_customer_quote_payment_profile_calculations_without_maintenance_test" time="80.531"/>
  <testcase classname="newCar.FL.Acquisition_Quotes_FL_PCH_with_funder_quote_addition_without_maintenance_Test" name="aquisition_quotes_FL_PCH_quote_summary_values_verification_without_maintenance_test" time="177.245">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at newCar.FL.Acquisition_Quotes_FL_PCH_with_funder_quote_addition_without_maintenance_Test.aquisition_quotes_FL_PCH_quote_summary_values_verification_without_maintenance_test(Acquisition_Quotes_FL_PCH_with_funder_quote_addition_without_maintenance_Test.java:186)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- aquisition_quotes_FL_PCH_quote_summary_values_verification_without_maintenance_test -->
</testsuite> <!-- Default test -->
